#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SuiteMatematica_AndroidCSharp.Resource", IsApplication=true)]

namespace SuiteMatematica_AndroidCSharp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int Operations = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int Operariones = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int btnIniciar = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int btnIniciarPractica = 2131099654;
			
			// aapt resource value: 0x7f060014
			public const int btnSiguiente = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int btnValidar = 2131099667;
			
			// aapt resource value: 0x7f06000b
			public const int button1 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int button2 = 2131099660;
			
			// aapt resource value: 0x7f060012
			public const int edittext = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int lblBien = 2131099669;
			
			// aapt resource value: 0x7f06000d
			public const int lblCantidad = 2131099661;
			
			// aapt resource value: 0x7f060018
			public const int lblLimite = 2131099672;
			
			// aapt resource value: 0x7f060016
			public const int lblMal = 2131099670;
			
			// aapt resource value: 0x7f06000e
			public const int lblN1 = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int lblN2 = 2131099664;
			
			// aapt resource value: 0x7f060017
			public const int lblReiniciado = 2131099671;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout1 = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int radioButton1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int radioButton2 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int radioButton3 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int radioButton4 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int radioButton5 = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int rbNivel = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int textView1 = 2131099655;
			
			// aapt resource value: 0x7f060011
			public const int txtEqual = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int txtPlus = 2131099663;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int lvlSelector = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Sumas = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int Divisiones = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int Intro_Main = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int Message_Main = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int Multiplicaciones = 2130968580;
			
			// aapt resource value: 0x7f04001b
			public const int RestartMessage = 2130968603;
			
			// aapt resource value: 0x7f040003
			public const int Restas = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int Start = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int Sumas = 2130968578;
			
			// aapt resource value: 0x7f04001a
			public const int WellMessage = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int WrongMessage = 2130968601;
			
			// aapt resource value: 0x7f04000b
			public const int btnAbout = 2130968587;
			
			// aapt resource value: 0x7f040011
			public const int btnIniciarPractica = 2130968593;
			
			// aapt resource value: 0x7f040009
			public const int btnMainIniciar = 2130968585;
			
			// aapt resource value: 0x7f040018
			public const int btnSiguiente = 2130968600;
			
			// aapt resource value: 0x7f04000a
			public const int btnStatistics = 2130968586;
			
			// aapt resource value: 0x7f040017
			public const int btnValidar = 2130968599;
			
			// aapt resource value: 0x7f040013
			public const int lblBien = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int lblCantidadDoIt = 2130968594;
			
			// aapt resource value: 0x7f040016
			public const int lblLimite = 2130968598;
			
			// aapt resource value: 0x7f040014
			public const int lblMal = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int lblReiniciado = 2130968597;
			
			// aapt resource value: 0x7f04000c
			public const int rbl1 = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int rbl2 = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int rbl3 = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int rbl4 = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int rbl5 = 2130968592;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
