#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SuiteMatematica_AndroidCSharp.Resource", IsApplication=true)]

namespace SuiteMatematica_AndroidCSharp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int Operations = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070008
			public const int Operariones = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int btnIniciar = 2131165193;
			
			// aapt resource value: 0x7f070006
			public const int btnIniciarPractica = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int button1 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int button2 = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int linearLayout1 = 2131165194;
			
			// aapt resource value: 0x7f070001
			public const int radioButton1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int radioButton2 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int radioButton3 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int radioButton4 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int radioButton5 = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int rbNivel = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int textView1 = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int lvlSelector = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000b
			public const int About = 2130968587;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int Divisiones = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int Intro_Main = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int Message_Main = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int Multiplicaciones = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int Restas = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int Start = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int Statistics = 2130968586;
			
			// aapt resource value: 0x7f040002
			public const int Sumas = 2130968578;
			
			// aapt resource value: 0x7f040011
			public const int btnIniciarPractica = 2130968593;
			
			// aapt resource value: 0x7f040009
			public const int btn_Main = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int rbl1 = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int rbl2 = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int rbl3 = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int rbl4 = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int rbl5 = 2130968592;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
