#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SuiteMatematica_AndroidCSharp.Resource", IsApplication=true)]

namespace SuiteMatematica_AndroidCSharp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int Operations = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040002
			public const int activity_horizontal_margin = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int activity_vertical_margin = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int nav_header_height = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int nav_header_vertical_spacing = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_shape = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int delete = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int gradient_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int gradient_bg_alternate = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int gradient_bg_hover = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int gradient_bg_hover_alternate = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int input_shape = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int list_selector = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int list_selector_alternate = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080008
			public const int Operariones = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int btnIniciar = 2131230729;
			
			// aapt resource value: 0x7f080006
			public const int btnIniciarPractica = 2131230726;
			
			// aapt resource value: 0x7f080014
			public const int btnSiguiente = 2131230740;
			
			// aapt resource value: 0x7f080013
			public const int btnValidar = 2131230739;
			
			// aapt resource value: 0x7f08000b
			public const int button1 = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int button2 = 2131230732;
			
			// aapt resource value: 0x7f08001b
			public const int contactList_btnSearch = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int contactList_listView = 2131230748;
			
			// aapt resource value: 0x7f08001a
			public const int contactList_txtSearch = 2131230746;
			
			// aapt resource value: 0x7f080012
			public const int edittext = 2131230738;
			
			// aapt resource value: 0x7f080015
			public const int lblBien = 2131230741;
			
			// aapt resource value: 0x7f08000d
			public const int lblCantidad = 2131230733;
			
			// aapt resource value: 0x7f080018
			public const int lblLimite = 2131230744;
			
			// aapt resource value: 0x7f080016
			public const int lblMal = 2131230742;
			
			// aapt resource value: 0x7f08000e
			public const int lblN1 = 2131230734;
			
			// aapt resource value: 0x7f080010
			public const int lblN2 = 2131230736;
			
			// aapt resource value: 0x7f080017
			public const int lblReiniciado = 2131230743;
			
			// aapt resource value: 0x7f08000a
			public const int linearLayout1 = 2131230730;
			
			// aapt resource value: 0x7f08001f
			public const int lr_bien = 2131230751;
			
			// aapt resource value: 0x7f080022
			public const int lr_deleteBtn = 2131230754;
			
			// aapt resource value: 0x7f080021
			public const int lr_fecha = 2131230753;
			
			// aapt resource value: 0x7f080020
			public const int lr_mal = 2131230752;
			
			// aapt resource value: 0x7f08001e
			public const int lr_nivel = 2131230750;
			
			// aapt resource value: 0x7f08001d
			public const int lr_operacion = 2131230749;
			
			// aapt resource value: 0x7f080001
			public const int radioButton1 = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int radioButton2 = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int radioButton3 = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int radioButton4 = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int radioButton5 = 2131230725;
			
			// aapt resource value: 0x7f080000
			public const int rbNivel = 2131230720;
			
			// aapt resource value: 0x7f080019
			public const int tableLayout = 2131230745;
			
			// aapt resource value: 0x7f080007
			public const int textView1 = 2131230727;
			
			// aapt resource value: 0x7f080011
			public const int txtEqual = 2131230737;
			
			// aapt resource value: 0x7f08000f
			public const int txtPlus = 2131230735;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int lvlSelector = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Multiplicaciones = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Restas = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Statistics = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Statistics_row = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Sumas = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int Divisiones = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int Intro_Main = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int Message_Main = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int Multiplicaciones = 2131034116;
			
			// aapt resource value: 0x7f05001b
			public const int RestartMessage = 2131034139;
			
			// aapt resource value: 0x7f050003
			public const int Restas = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int Start = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int Sumas = 2131034114;
			
			// aapt resource value: 0x7f05001a
			public const int WellMessage = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int WrongMessage = 2131034137;
			
			// aapt resource value: 0x7f05001f
			public const int bien = 2131034143;
			
			// aapt resource value: 0x7f05000b
			public const int btnAbout = 2131034123;
			
			// aapt resource value: 0x7f050011
			public const int btnIniciarPractica = 2131034129;
			
			// aapt resource value: 0x7f050009
			public const int btnMainIniciar = 2131034121;
			
			// aapt resource value: 0x7f050018
			public const int btnSiguiente = 2131034136;
			
			// aapt resource value: 0x7f05000a
			public const int btnStatistics = 2131034122;
			
			// aapt resource value: 0x7f050017
			public const int btnValidar = 2131034135;
			
			// aapt resource value: 0x7f050021
			public const int fecha = 2131034145;
			
			// aapt resource value: 0x7f05001c
			public const int id = 2131034140;
			
			// aapt resource value: 0x7f050013
			public const int lblBien = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int lblCantidadDoIt = 2131034130;
			
			// aapt resource value: 0x7f050016
			public const int lblLimite = 2131034134;
			
			// aapt resource value: 0x7f050014
			public const int lblMal = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int lblReiniciado = 2131034133;
			
			// aapt resource value: 0x7f050020
			public const int mal = 2131034144;
			
			// aapt resource value: 0x7f05001e
			public const int nivel = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int operacion = 2131034141;
			
			// aapt resource value: 0x7f05000c
			public const int rbl1 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int rbl2 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int rbl3 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int rbl4 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int rbl5 = 2131034128;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int button_style = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int input_style = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
